Fix build with gcc-12
:Release Notes:
Fixes:
  http://gecko.lge.com/Errors/Details/400131

:Detailed Notes:
FAILED: src/CMakeFiles/unifiedsearch.dir/util/LinuxProcess.cpp.o
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/recipe-sysroot-native/usr/bin/aarch64-webos-linux/aarch64-webos-linux-g++  -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/recipe-sysroot/usr/include/glib-2.0 -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/recipe-sysroot/usr/lib/glib-2.0/include -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/git/src/PROCPS_INCLUDE_DIRS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/git/src/SQLITE3_INCLUDE_DIRS -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/git/src -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/git/src/../core -ITOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/build/Configured/src -mcpu=cortex-a72 -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Werror=return-type  --sysroot=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1=/usr/src/debug/com.webos.service.unifiedsearch/1.0.0-6-r1                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1=/usr/src/debug/com.webos.service.unifiedsearch/1.0.0-6-r1                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/recipe-sysroot-native=  -fvisibility-inlines-hidden  -std=c++0x -DNDEBUG -MD -MT src/CMakeFiles/unifiedsearch.dir/util/LinuxProcess.cpp.o -MF src/CMakeFiles/unifiedsearch.dir/util/LinuxProcess.cpp.o.d -o src/CMakeFiles/unifiedsearch.dir/util/LinuxProcess.cpp.o -c TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/git/src/util/LinuxProcess.cpp
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/git/src/util/LinuxProcess.cpp: In static member function 'static std::string LinuxProcess::getStdoutFromCmd(const std::string&)':
TOPDIR/BUILD/work/raspberrypi4_64-webos-linux/com.webos.service.unifiedsearch/1.0.0-6-r1/git/src/util/LinuxProcess.cpp:208:22: error: aggregate 'std::array<char, 128> buffer' has incomplete type and cannot be defined
  208 |     array<char, 128> buffer;
      |                      ^~~~~~

:Testing Performed:
Only build tested.

:QA Notes:
No change to image.

:Issues Addressed:
[WRP-10791] CCC: Various build fixes

Change-Id: Ie555d4f5eabeb85b9e93b4da9e23df2c88c11c45
Reviewed-on: http://gpro.lge.com/c/webosose/com.webos.service.unifiedsearch/+/347405
Tested-by: Sangwoo Kang <sangwoo82.kang@lge.com>
Reviewed-by: Sangwoo Kang <sangwoo82.kang@lge.com>